general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a batch script to start Zebar.
  startup_commands: ["shell-exec %userprofile%/.glzr/zebar/start.bat"]

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

gaps:
  # Gap between adjacent windows.
  inner_gap: "20px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "60px"
    right: "20px"
    bottom: "20px"
    left: "20px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#8dbcff"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys.PowerAccent" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper*" }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["l", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["h", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

  # When enabled, all keybindings are disabled except for escape+shift+p which
  # returns to default keybindings.
  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["escape+shift+p"]

keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["escape+h", "alt+left"]
  - commands: ["focus --direction right"]
    bindings: ["escape+l", "alt+right"]
  - commands: ["focus --direction up"]
    bindings: ["escape+k", "alt+up"]
  - commands: ["focus --direction down"]
    bindings: ["escape+j", "alt+down"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["escape+ctrl+h", "alt+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["escape+ctrl+l", "alt+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["escape+ctrl+k", "alt+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["escape+ctrl+j", "alt+shift+down"]

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -2%"]
    bindings: ["escape+shift+l"]
  - commands: ["resize --width +2%"]
    bindings: ["escape+shift+h"]
  - commands: ["resize --height +2%"]
    bindings: ["escape+shift+k"]
  - commands: ["resize --height -2%"]
    bindings: ["escape+shift+j"]

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["escape+r"]

  # Disables all keybindings until escape+shift+p is pressed again.
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["escape+shift+p"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["escape+v"]

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ["wm-cycle-focus"]
    bindings: ["escape+space"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["escape+shift+f"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["escape+t"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["escape+f"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["escape+m"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["escape+q"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["escape+shift+c"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["escape+shift+r"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["escape+shift+w"]

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ["shell-exec wt"]
    bindings: ["escape+enter"]

  - commands: ['shell-exec %LOCALAPPDATA%\BraveSoftware\Brave-Browser\Application\brave.exe']
    bindings: ["escape+w"]

  - commands: ['shell-exec %ProgramFiles%\Mozilla Thunderbird\thunderbird.exe']
    bindings: ["escape+e"]

  - commands: ['shell-exec %USERPROFILE%\Scripts\run.vbs']
    bindings: ["escape+d"]

  - commands: ['shell-exec %USERPROFILE%\scoop\apps\btop\current\btop.exe']
    bindings: ["escape+shift+r"]

  - commands: ['shell-exec files.exe']
    bindings: ["escape+r"]

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ["focus --next-workspace"]
    bindings: ["escape+s"]
  - commands: ["focus --prev-workspace"]
    bindings: ["escape+a"]

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["escape+shift+d"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["escape+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["escape+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["escape+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["escape+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["escape+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["escape+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["escape+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["escape+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["escape+9"]

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ["move-workspace --direction left"]
    bindings: ["escape+shift+a"]
  - commands: ["move-workspace --direction right"]
    bindings: ["escape+shift+f"]
  - commands: ["move-workspace --direction up"]
    bindings: ["escape+shift+d"]
  - commands: ["move-workspace --direction down"]
    bindings: ["escape+shift+s"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["escape+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["escape+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["escape+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["escape+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["escape+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["escape+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["escape+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["escape+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["escape+shift+9"]
